server:
  port: 8888
  servlet:
    context-path: /
spring:
  mvc:
    format:
      date-time: yyyy-MM-dd
  jackson:
    date-format: yyyy-MM-dd
    locale: zh_CN
springfox:
  documentation:
    swagger:
      v2:
        enabled: true

